cosas = [5, 6.7, "hola", False, "programacion", True, 9]
print(cosas)
print(cosas[2])
print(cosas[0])
print(cosas[0]+cosas[1])
print(cosas[2]+" " + cosas[4])
print(len(cosas))
print(cosas[0:3])
print(cosas[5:7])
print(cosas[0:7:2])
print(cosas[::2])
print(cosas[::-2])